name = "Arc Nectar"
author = "Sewdohe"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "382e86345e501bbfb3e0fcb67d3ab20001f595b803b7dea3fefc0654c004b3df"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
