name = "Arc Nectar"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aef6cb9717b21af9d863db4e87603d0a13e051ca61055bff7950f40b342a7e82"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
