name = "Arc Nectar"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0693b3b404c27f924b8db935eaca2e58997124f01b59c9bb2bfdf8fbc422d263"

[versions]
forge = "47.2.20"
minecraft = "1.20.1"
